<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ImageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('images')->insert([
            [
                'name' => 'banner1',
                'src' => 'banner1.jpg',
                'article_id' => null,
                'product_id' => null,
                'pp' => false,
            ],
            [
                'name' => 'banner2',
                'src' => 'banner2.jpg',
                'article_id' => null,
                'product_id' => null,
                'pp' => false,
            ],
            [
                'name' => 'banner3',
                'src' => 'banner3.jpg',
                'article_id' => null,
                'product_id' => null,
                'pp' => false,
            ],
            [
                'name' => 'banner4',
                'src' => 'banner4.jpg',
                'article_id' => null,
                'product_id' => null,
                'pp' => false,
            ],
            [
                'name' => 'banner5',
                'src' => 'banner5.jpg',
                'article_id' => null,
                'product_id' => null,
                'pp' => false,
            ],
            [
                'name' => 'banner6',
                'src' => 'banner6.jpg',
                'article_id' => null,
                'product_id' => null,
                'pp' => false,
            ],
            [
                'name' => 'banner7',
                'src' => 'banner7.jpg',
                'article_id' => null,
                'product_id' => null,
                'pp' => false,
            ],
            [
                'name' => 'banner8',
                'src' => 'banner8.jpg',
                'article_id' => null,
                'product_id' => null,
                'pp' => false,
            ],
            [
                'name' => 'banner9',
                'src' => 'banner9.jpg',
                'article_id' => null,
                'product_id' => null,
                'pp' => false,
            ],
            [
                'name' => 'banner10',
                'src' => 'banner10.jpg',
                'article_id' => null,
                'product_id' => null,
                'pp' => false,
            ],
            [
                'name' => 'banner11',
                'src' => 'banner11.jpg',
                'article_id' => null,
                'product_id' => null,
                'pp' => false,
            ],
            [
                'name' => 'banner12',
                'src' => 'banner12.jpg',
                'article_id' => null,
                'product_id' => null,
                'pp' => false,
            ],
            [
                'name' => 'meuble1',
                'src' => 'meuble1.jpg',
                'article_id' => null,
                'product_id' => 1,
                'pp' => true,
            ],
            [
                'name' => 'meuble2',
                'src' => 'meuble2.jpg',
                'article_id' => null,
                'product_id' => 2,
                'pp' => true,
            ],
            [
                'name' => 'meuble3',
                'src' => 'meuble3.jpg',
                'article_id' => null,
                'product_id' => 3,
                'pp' => true,
            ],
            [
                'name' => 'meuble4',
                'src' => 'meuble4.jpg',
                'article_id' => null,
                'product_id' => 4,
                'pp' => true,
            ],
            [
                'name' => 'meuble5',
                'src' => 'meuble5.jpg',
                'article_id' => null,
                'product_id' => 5,
                'pp' => true,
            ],
            [
                'name' => 'meuble6',
                'src' => 'meuble6.jpg',
                'article_id' => null,
                'product_id' => 6,
                'pp' => true,
            ],
            [
                'name' => 'meuble7',
                'src' => 'meuble7.jpg',
                'article_id' => null,
                'product_id' => 7,
                'pp' => true,
            ],
            [
                'name' => 'meuble8',
                'src' => 'meuble8.jpg',
                'article_id' => null,
                'product_id' => 8,
                'pp' => true,
            ],
            [
                'name' => 'blog1',
                'src' => 'blog1.jpg',
                'article_id' => 1,
                'product_id' => null,
                'pp' => false,
            ],
            [
                'name' => 'blog2',
                'src' => 'blog2.jpg',
                'article_id' => 2,
                'product_id' => null,
                'pp' => false,
            ],
            [
                'name' => 'blog3',
                'src' => 'blog3.jpg',
                'article_id' => 3,
                'product_id' => null,
                'pp' => false,
            ],
            [
                'name' => 'blog4',
                'src' => 'blog4.jpg',
                'article_id' => 4,
                'product_id' => null,
                'pp' => false,
            ],
            [
                'name' => 'blog5',
                'src' => 'blog5.jpg',
                'article_id' => 5,
                'product_id' => null,
                'pp' => false,
            ],
            [
                'name' => 'blog6',
                'src' => 'blog6.jpg',
                'article_id' => 6,
                'product_id' => null,
                'pp' => false,
            ],
            [
                'name' => 'blog7',
                'src' => 'blog7.jpg',
                'article_id' => 7,
                'product_id' => null,
                'pp' => false,
            ],
            [
                'name' => 'blog8',
                'src' => 'blog8.jpg',
                'article_id' => null,
                'product_id' => null,
                'pp' => false,
            ],
            [
                'name' => 'blog9',
                'src' => 'blog9.jpg',
                'article_id' => null,
                'product_id' => null,
                'pp' => false,
            ],
            [
                'name' => 'blog10',
                'src' => 'blog10.jpg',
                'article_id' => null,
                'product_id' => null,
                'pp' => false,
            ],
            [
                'name' => 'blog11',
                'src' => 'blog11.jpg',
                'article_id' => null,
                'product_id' => null,
                'pp' => false,
            ],
            [
                'name' => 'details1',
                'src' => 'details1.jpg',
                'article_id' => null,
                'product_id' => 1,
                'pp' => false,
            ],
            [
                'name' => 'details2',
                'src' => 'details2.jpg',
                'article_id' => null,
                'product_id' => 1,
                'pp' => false,
            ],
            [
                'name' => 'details3',
                'src' => 'details3.jpg',
                'article_id' => null,
                'product_id' => 1,
                'pp' => false,
            ],
            [
                'name' => 'details4',
                'src' => 'details4.jpg',
                'article_id' => null,
                'product_id' => 2,
                'pp' => false,
            ],
            [
                'name' => 'details5',
                'src' => 'details5.jpg',
                'article_id' => null,
                'product_id' => 2,
                'pp' => false,
            ],
            [
                'name' => 'details6',
                'src' => 'details6.jpg',
                'article_id' => null,
                'product_id' => 2,
                'pp' => false,
            ],
            [
                'name' => 'details7',
                'src' => 'details7.jpg',
                'article_id' => null,
                'product_id' => 3,
                'pp' => false,
            ],
            [
                'name' => 'details8',
                'src' => 'details8.jpg',
                'article_id' => null,
                'product_id' => 3,
                'pp' => false,
            ],
            [
                'name' => 'details9',
                'src' => 'details9.jpg',
                'article_id' => null,
                'product_id' => 3,
                'pp' => false,
            ],
            [
                'name' => 'details10',
                'src' => 'details10.jpg',
                'article_id' => null,
                'product_id' => 4,
                'pp' => false,
            ],
            [
                'name' => 'details11',
                'src' => 'details11.jpg',
                'article_id' => null,
                'product_id' => 4,
                'pp' => false,
            ],
            [
                'name' => 'details12',
                'src' => 'details12.jpg',
                'article_id' => null,
                'product_id' => 4,
                'pp' => false,
            ],
            [
                'name' => 'details13',
                'src' => 'details13.jpg',
                'article_id' => null,
                'product_id' => 4,
                'pp' => false,
            ],
            [
                'name' => 'details14',
                'src' => 'details14.jpg',
                'article_id' => null,
                'product_id' => 5,
                'pp' => false,
            ],
            [
                'name' => 'details15',
                'src' => 'details15.jpg',
                'article_id' => null,
                'product_id' => 5,
                'pp' => false,
            ],
            [
                'name' => 'details16',
                'src' => 'details16.jpg',
                'article_id' => null,
                'product_id' => 5,
                'pp' => false,
            ],
            [
                'name' => 'details17',
                'src' => 'details17.jpg',
                'article_id' => null,
                'product_id' => 6,
                'pp' => false,
            ],
            [
                'name' => 'details18',
                'src' => 'details18.jpg',
                'article_id' => null,
                'product_id' => 6,
                'pp' => false,
            ],
            [
                'name' => 'details19',
                'src' => 'details19.jpg',
                'article_id' => null,
                'product_id' => 6,
                'pp' => false,
            ],
            [
                'name' => 'details20',
                'src' => 'details20.jpg',
                'article_id' => null,
                'product_id' => 7,
                'pp' => false,
            ],
            [
                'name' => 'details21',
                'src' => 'details21.jpg',
                'article_id' => null,
                'product_id' => 7,
                'pp' => false,
            ],
            [
                'name' => 'details22',
                'src' => 'details22.jpg',
                'article_id' => null,
                'product_id' => 7,
                'pp' => false,
            ],
            [
                'name' => 'details23',
                'src' => 'details23.jpg',
                'article_id' => null,
                'product_id' => 7,
                'pp' => false,
            ],
            [
                'name' => 'details24',
                'src' => 'details24.jpg',
                'article_id' => null,
                'product_id' => 8,
                'pp' => false,
            ],
            [
                'name' => 'details25',
                'src' => 'details25.jpg',
                'article_id' => null,
                'product_id' => 8,
                'pp' => false,
            ],
            [
                'name' => 'details26',
                'src' => 'details26.jpg',
                'article_id' => null,
                'product_id' => 8,
                'pp' => false,
            ],
            [
                'name' => 'details27',
                'src' => 'details27.jpg',
                'article_id' => null,
                'product_id' => 8,
                'pp' => false,
            ],
            [
                'name' => 'details28',
                'src' => 'details28.jpg',
                'article_id' => null,
                'product_id' => 1,
                'pp' => false,
            ],
            [
                'name' => 'details29',
                'src' => 'details29.jpg',
                'article_id' => null,
                'product_id' => 2,
                'pp' => false,
            ],
            [
                'name' => 'details30',
                'src' => 'details30.jpg',
                'article_id' => null,
                'product_id' => 3,
                'pp' => false,
            ],
        ]);
    }
}
